### ISSUE TITLE
缩略图问题

### ISSUE THREAD

**Issue by moyiza-app** [adam198824/cordova-plugin-wechat#1]
装了最新版本，3.0.6 但还是有缩略图问题。
请问，这个缩略图是基于本地图片的吗？
比如thumb值能否为网络图片地址？

**Comment by adampidong** [comment]
你是使用那个方法有缩略图问题？我分享这块没这个问题，thumb目前是使用网络图片地址，不支持本地图片

**Comment by moyiza-app** [comment]
有大小限制吗？以前用了xu-li的插件，但好像在ios不能编译，装了这个好像可以，所以安卓也改成这个，但ios能显示图片，安卓不能，只显示app icon

**Comment by adampidong** [comment]
你是用那个方法不能显示图片？
大小限制你去看微信的文档
这个就是基于xu-li的修改的，他不维护了。

**Comment by moyiza-app** [comment]
你的在android也正常显示，是吧？

**Comment by adampidong** [comment]
我一直问的都是你用的那个方法缩略图不显示？

**Comment by adampidong** [comment]
我一直问的都是你用的那个方法缩略图不显示？

**Comment by moyiza-app** [comment]
就是 Wechat.share 方法呀

**Comment by moyiza-app** [comment]
发送给朋友和朋友圈都一样

**Comment by adampidong** [comment]
你使用网络图片就可以了

**Comment by moyiza-app** [comment]
我用的就是网络图片啊

**Comment by moyiza-app** [comment]
thumb值就是一个网络图片地址

**Comment by adampidong** [comment]
我这里ios和安卓都可以。

**Comment by moyiza-app** [comment]
试过很多尺寸，都不行啊，你的cordova和android platform的版本是多少啊

**Comment by adampidong** [comment]
cordova是8.0.0
cordova-android是7.0.0
目前plugin只支持7.0以上的

**Comment by moyiza-app** [comment]
我的cordova是8.1.2
android是7.1.1
不会是版本太高的问题吧

**Comment by adampidong** [comment]
有可能，你降级下试试看

**Comment by moyiza-app** [comment]
版本改成和你一样的，还是没有缩略图呀，能看一下你的config.xml吗

**Comment by moyiza-app** [comment]
我的分享用了 Share link ，但这个link不能带缩略图

**Comment by moyiza-app** [comment]
大概知道原因了，我用红米note5就没有缩略图，但用三星note5就有缩略图，应该是机型的问题，可能小米对android的修改导致这个插件出问题。先这样了，谢谢答复！
