### ISSUE TITLE
微信支付掉不起来，返回普通错误

### ISSUE THREAD

**Issue by danli92** [adam198824/cordova-plugin-wechat#3]
微信支付掉不起来，返回普通错误，签名什么的也检查过了。不知道什么原因。

**Comment by YDJSZY** [comment]
同样，普通错误。。。。

**Comment by chaoyuz** [comment]
> 同样，普通错误。。。。

请问 普通错误解决了吗 入坑了 2天了

**Comment by adampidong** [comment]
普通错误最大的可能是参数错了，就对照文档调试参数，并且微信的文档有时候更新并不及时，另外，发问题也请标明版本是ios还是安卓，谢谢。
