### ISSUE TITLE
安装遇到如下问题

### ISSUE THREAD

**Issue by robinlin0402** [adam198824/cordova-plugin-wechat#6]
Failed to install 'cordova-plugin-adam-wechat': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by robinlin0402** [comment]
安装在

**Comment by robinlin0402** [comment]
Failed to install 'cordova-plugin-adam-wechat': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by jammind** [comment]
Me, too. Anyone fixed it?
