### ISSUE TITLE
安装出现错误

### ISSUE THREAD

**Issue by robinlin0402** [adam198824/cordova-plugin-wechat#7]
Failed to install 'cordova-plugin-adam-wechat': CordovaError: Using "requireCordovaModule" to load non-cordova module "path" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by whj-henry** [comment]
同上,我也是这个提示

**Comment by jammind** [comment]
我也是一样的问题，有人装成功了吗？

**Comment by adampidong** [comment]
请说明下你的Cordova版本
